# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-app-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-app-ios

  target 'sample-app-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample-app-iosUITests' do
    # Pods for testing
  end

  pod 'sharedui', :path => '../shared-ui'
#   pod 'shareddata', :path => '../shared-data'
end
